### ISSUE TITLE
Implement fetching without cursor

### ISSUE THREAD

**Issue by ruscoder** [Brogency/baobab-react-resolver#12]

**Comment by ir4y** [comment]
Why do we need it?

**Comment by ruscoder** [comment]
Sometimes we don't need to store data from the API. For example, we can make a request to the API with 'HEAD' method. It might be helpful for checking permissions in root components. 

It is connected to #11.

**Comment by ir4y** [comment]
But need to store information about 'HEAD' method somewhere.
How our interface should know that it has/has not permissions to something.
This information should be placed somewhere.

**Comment by ruscoder** [comment]
Sure. I've missed it.
